ACS-6309 fix reportportal dependencies
Alfresco/acs-community-packaging pull request #1555
Opened 2024-04-15 14:16 UTC by wojtekswieton

2024-04-15 14:24 UTC, dsibilio requested changes

2024-04-15 14:24 UTC, dsibilio commented on tests/tas-cmis/pom.xml
> +            <version>5.4.0</version>
The version should be unnecessary, it should already be handled via the `dependencyManagement` of the parent POM. Can we test removing it?

2024-04-15 14:24 UTC, dsibilio commented on tests/tas-email/pom.xml
> +            <version>5.4.0</version>
Same as above.

2024-04-15 14:24 UTC, dsibilio commented on tests/tas-integration/pom.xml
> +            <version>5.4.0</version>
Same as above.

2024-04-15 14:24 UTC, dsibilio commented on tests/tas-restapi/pom.xml
> +            <version>5.4.0</version>
Same as above.

2024-04-15 14:24 UTC, dsibilio commented on tests/tas-webdav/pom.xml
> +            <version>5.4.0</version>
Same as above.

2024-04-15 14:29 UTC, dsibilio requested changes

2024-04-15 14:29 UTC, dsibilio commented on tests/tas-cmis/pom.xml
> +            <version>5.4.0</version>
```suggestion
```

2024-04-15 14:29 UTC, dsibilio commented on tests/tas-email/pom.xml
> +            <version>5.4.0</version>
```suggestion
```

2024-04-15 14:29 UTC, dsibilio commented on tests/tas-integration/pom.xml
> +            <version>5.4.0</version>
```suggestion
```

2024-04-15 14:29 UTC, dsibilio commented on tests/tas-restapi/pom.xml
> +            <version>5.4.0</version>
```suggestion
```

2024-04-15 14:29 UTC, dsibilio commented on tests/tas-webdav/pom.xml
> +            <version>5.4.0</version>
```suggestion
```

2024-04-16 08:08 UTC, dsibilio approved these changes

2024-04-16 08:21 UTC, aonych approved these changes

2024-04-16 08:46 UTC, merged