ACS-7683 Prepare for ACS 7.3.2 Service Pack
Alfresco/acs-community-packaging pull request #1556
Opened 2024-04-23 09:01 UTC by mikolajbrzezinski

2024-04-23 09:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/acs-community-packaging?pullRequest=1556) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/acs-community-packaging?pullRequest=1556) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: mikolajbrzezinski<br/>:white_check_mark: krdabrowski<br/>:white_check_mark: dsibilio<br/>:white_check_mark: damianujma<br/>:white_check_mark: pzhyland<br/>:x: Travis CI User<br/><hr/>**Travis CI User** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/acs-community-packaging?pullRequest=1556) it.</sub>

2024-04-23 12:43 UTC, aonych approved these changes

2024-04-23 12:46 UTC, aonych commented on .github/workflows/ci.yml
> +  RELEASE_VERSION: 7.3.1
Shouldn't the RELEASE_VERSION be 7.3.2-A2?

2024-04-23 14:41 UTC, dsibilio requested changes
Remember to also roll back the -SNAPSHOT changes in the `pom.xml` before merging.

2024-04-23 14:41 UTC, dsibilio commented on .github/workflows/ci.yml
> +  RELEASE_VERSION: 7.3.1
```suggestion
  RELEASE_VERSION: 7.3.2-A2
```

2024-04-24 06:48 UTC, aonych approved these changes

2024-04-24 07:46 UTC, dsibilio approved these changes

2024-04-24 07:46 UTC, merged